nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        max_age: 0
    paths:
        '^/auth/login$':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['POST']
            allow_headers: ['*']
            max_age: 30
        '^/auth/token/refresh$':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['POST']
            allow_headers: ['*']
            max_age: 3600
        '^/auth/register$':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['POST']
            allow_headers: ['*']
            max_age: 3600
        '^/api/task/create$':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['POST']
            allow_headers: ['*']
            max_age: 3600
        '^/api/task/finish/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['PATCH']
            allow_headers: ['*']
            max_age: 3600
        '^/api/task/delete/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['PATCH']
            allow_headers: ['*']
            max_age: 3600
        '^/api/tasks/getTodaysTasks$':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            origin_regex: true
            allow_methods: ['GET']
            allow_headers: ['*']
            max_age: 3600