prooph_event_store:
    stores:
        tasker_store:
            event_store: '@prooph_event_store.mysql_event_store.tasker_store'
            repositories:
                task_repository:
                    repository_class: Tasker\Infrastructure\Repository\TaskEventStore
                    aggregate_type: Tasker\Model\Task\Domain\Task
                    aggregate_translator: prooph_event_sourcing.aggregate_translator


services:
    prooph_event_store.mysql_event_store.tasker_store:
        class: Prooph\EventStore\Pdo\MySqlEventStore
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator