prooph_event_store:
    stores:
        tasker_store:
            event_store: '@prooph_event_store.mysql_event_store.tasker_store'
            repositories:
                task_repository:
                    repository_class: Tasker\Infrastructure\Repository\TaskEventStore
                    aggregate_type: Tasker\Model\Task\Domain\Task
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        task_projection_manager:
            event_store: '@prooph_event_store.mysql_event_store.tasker_store'
            connection: '@doctrine.pdo.connection'
            event_streams_table: event_streams
            projections_table: projections
            projections:
                task_projection:
                    read_model: '@prooph_event_store.read_model.task_read_model'
                    projection: '@prooph_event_store.projection.task_projection'
                open_task_projection:
                    read_model: '@prooph_event_store.read_model.open_task_read_model'
                    projection: '@prooph_event_store.projection.open_task_projection'

services:
    prooph_event_store.mysql_event_store.tasker_store:
        class: Prooph\EventStore\Pdo\MySqlEventStore
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    prooph_event_store.projection.task_projection:
        class: Tasker\Infrastructure\Projection\Task\TaskProjection

    prooph_event_store.read_model.task_read_model:
        class: Tasker\Infrastructure\Projection\Task\TaskReadModel
        arguments: ['@mongo.connection.default']

    prooph_event_store.projection.open_task_projection:
        class: Tasker\Infrastructure\Projection\Task\OpenTaskProjection

    prooph_event_store.read_model.open_task_read_model:
        class: Tasker\Infrastructure\Projection\Task\OpenTaskReadModel
        arguments: ['@mongo.connection.default']

    prooph_event_store.finder.task_finder:
        class: Tasker\Infrastructure\Projection\Task\TaskFinder
        arguments: ['@mongo.connection.default']