prooph_service_bus:
    command_buses:
        tasker_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'

        user_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'

    query_buses:
        tasker_query_bus:
            router:
                type: 'prooph_service_bus.query_bus_router'
                routes:
                    'Tasker\Model\Task\Query\GetTaskById': '@Tasker\Model\Task\QueryHandler\GetTaskByIdHandler'
                    'Tasker\Model\Task\Query\GetTasksByUserId': '@Tasker\Model\Task\QueryHandler\GetTasksByUserIdHandler'
                    'Tasker\Model\Task\Query\GetUserTodaysTasks': '@Tasker\Model\Task\QueryHandler\GetUserTodaysTasksHandler'
                    'Tasker\Model\Task\Query\GetUserOpenTasksForNextDays': '@Tasker\Model\Task\QueryHandler\GetUserOpenTasksForNextDaysHandler'