# Auth routes

login:
    path: /auth/login

register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: POST

# Tasker routes

create_task:
    path: /api/create_task
    controller: App\Controller\ApiController::postAction
    defaults: { command: 'Tasker\Model\Task\Command\CreateTask' }
    methods: POST