# Auth routes

login:
    path: /auth/login
    methods: POST

refresh_token:
    path: /auth/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: POST

register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: POST

# Tasker routes

create_task:
    path: /api/task/create
    controller: App\Controller\ApiController::postAction
    defaults: { command: 'Tasker\Model\Task\Command\CreateTask' }
    methods: POST