parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Tasker,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Controllers

    App\Controller\ApiController:
        arguments: ['@prooph_service_bus.tasker_command_bus', '@prooph_service_bus.message_factory']
        tags: ['controller.service_arguments']

    App\Controller\AuthController:
        arguments: ['@prooph_service_bus.user_command_bus', '@prooph_service_bus.message_factory']
        tags: ['controller.service_arguments']

    # Console commands

    App\Command\CreateEventStreamCommand:
        arguments: ['@prooph_event_store.mysql_event_store.tasker_store']

    # Command handlers - task context

    Tasker\Model\Task\CommandHandler\CreateTaskHandler:
        arguments: ['@task_repository']
        tags:
            - { name: 'prooph_service_bus.tasker_command_bus.route_target', message_detection: true }

    # Command handlers - user context

    Tasker\Model\User\CommandHandler\RegisterUserHandler:
        tags:
            - { name: 'prooph_service_bus.user_command_bus.route_target', message_detection: true }
