Tasker\Model\User\Domain\UserPassword:
    type: embeddable
    fields:
        hashedPassword:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: password