Tasker\Model\User\Domain\UserEmail:
    type: embeddable
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false